USE [AGABRENWILL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[INSERIR_DADOS_INICIAIS_CLIENTE](
@NOME					VARCHAR(255),
@SOBRENOME				VARCHAR(255),
@DT_NASC				DATE = NULL,
@CPF					VARCHAR(11),
@RG						VARCHAR(15) = NULL,
@NACIONALIDADE			VARCHAR(255),
@PROFISSAO				VARCHAR(255),
@ID_ESTADO_CIVIL		INT,

@DDD					INT = NULL,
@TELEFONE				INT = NULL,

@RUA					VARCHAR(255),
@NUMERO					VARCHAR(255),
@BAIRRO					VARCHAR(255),
@MUNICIPIO				VARCHAR(255),
@ESTADO					VARCHAR(2),
@ID_TIPO_ENDERECO		VARCHAR(255),

@DT_ASSINATURA			DATETIME = NULL,
@DT_INICIO_CONTRATO		DATETIME = NULL,
@DT_FIM_PREVISTA		DATETIME = NULL,
@VL_TOTAL_CONTRATO      DECIMAL (10,2),
@ID_GRUPO_REGRA_DISTRIBUICAO INT
)
AS
BEGIN
	DECLARE @ID_CLIENTE INT

	IF ((SELECT DBO.VALIDAR_CPF(@CPF) AS RESULTADO) = 1) 
	BEGIN 
	--SELECT 'ENTROU' 
	--END
		INSERT INTO CLIENTE (NOME, SOBRENOME, DT_NASC, CPF, RG, NACIONALIDADE, PROFISSAO, ID_ESTADO_CIVIL)
		VALUES ( UPPER(@NOME), UPPER(@SOBRENOME), @DT_NASC, @CPF, @RG, UPPER(@NACIONALIDADE), UPPER(@PROFISSAO), @ID_ESTADO_CIVIL )

		SET @ID_CLIENTE = (SELECT TOP 1 ID_CLIENTE FROM CLIENTE WHERE CPF = @CPF)

		INSERT INTO ENDERECO ( RUA, NUMERO, BAIRRO, MUNICIPIO, ESTADO, ID_CLIENTE, ID_TIPO_ENDERECO )
		VALUES ( UPPER(@RUA), UPPER(@NUMERO), UPPER(@BAIRRO), UPPER(@MUNICIPIO), UPPER(@ESTADO), UPPER(@ID_CLIENTE), UPPER(@ID_TIPO_ENDERECO) )
			
		IF (@DDD IS NOT NULL OR @TELEFONE IS NOT NULL) 
		BEGIN 
			INSERT INTO TELEFONE (DDD, TELEFONE, ID_CLIENTE, ATIVO)
			VALUES ( @DDD, @TELEFONE, @ID_CLIENTE, 1)
		END

		INSERT INTO CONTRATO (ID_CLIENTE, DT_ASSINATURA, DT_INICIO_CONTRATO, DT_FIM_PREVISTA_CONTRATO, VL_TOTAL_CONTRATO, ID_GRUPO_REGRA_DISTRIBUICAO)
		VALUES (@ID_CLIENTE, @DT_ASSINATURA, @DT_INICIO_CONTRATO, @DT_FIM_PREVISTA, @VL_TOTAL_CONTRATO, @ID_GRUPO_REGRA_DISTRIBUICAO)

		SELECT * FROM CLIENTE C
		JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
		JOIN TELEFONE T	ON C.ID_CLIENTE = T.ID_CLIENTE
		JOIN CONTRATO O	ON C.ID_CLIENTE = O.ID_CLIENTE
		WHERE C.ID_CLIENTE = @ID_CLIENTE 

	END
	ELSE
	BEGIN 
		SELECT 'O NÚMERO DE CPF INFORMADO É INVALIDO, FAVOR VERIFICAR' 
	END
END

GO


