USE [AGABRENWILL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[INSERIR_TRANSACAO]
(
@ADM_OU_CRT VARCHAR(3),
@DT_TRANSACAO DATETIME,
@VL_TRANSACAO DECIMAL(10,2),
@ID_TIPO_TRANSACAO INT,
@ID_STATUS_TRANSACAO INT,
@ID_CONTRATO INT = NULL, -- SE NÃO FOR ADMINISTRATIVA
@DE_TRANSACAO VARCHAR(255),
@DE_TIPO_TRANSACAO VARCHAR(255),
@DT_LIMITE DATETIME = NULL
)
AS
BEGIN

IF (@ADM_OU_CRT = 'CRT')
	BEGIN
	IF (@ADM_OU_CRT IS NULL)
	BEGIN
		SELECT 'PARA TRANSAÇÕES DO TIPO CRT FAVOR INFORMAR O @ID_CONTRATO!!'
	END
		INSERT INTO [dbo].[TRANSACAO_CONTRATO_ADITIVO] ([DT_TRANSACAO], [VL_TRANSACAO], [DE_TRANSACAO], [DE_TIPO_TRANSACAO], [ID_TIPO_TRANSACAO], [ID_STATUS_TRANSACAO], [ID_CONTRATO], [DT_LIMITE])
		 VALUES ( @DT_TRANSACAO, @VL_TRANSACAO, @DE_TRANSACAO, @DE_TIPO_TRANSACAO, @ID_TIPO_TRANSACAO, @ID_STATUS_TRANSACAO, @ID_CONTRATO, @DT_LIMITE )
	END
IF (@ADM_OU_CRT = 'ADM')
	BEGIN
		INSERT INTO [dbo].[TRANSACAO_ADMINISTRATIVA] ([DT_TRANSACAO], [VL_TRANSACAO], [DE_TRANSACAO], [DE_TIPO_TRANSACAO], [ID_TIPO_TRANSACAO], [ID_STATUS_TRANSACAO], [DT_LIMITE])
		 VALUES ( @DT_TRANSACAO, @VL_TRANSACAO, @DE_TRANSACAO, @DE_TIPO_TRANSACAO, @ID_TIPO_TRANSACAO, @ID_STATUS_TRANSACAO, @DT_LIMITE )
	END
ELSE
	BEGIN
		SELECT 'FAVOR INFORMAR EM @ADM_OU_CRT SE É ADM OU CRT!!'
	END

END
GO


