USE [AGABRENWILL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TIPO_TRANSACAO](
	[ID_TIPO_TRANSACAO] [int] IDENTITY(1,1) NOT NULL,
	[NM_TIPO_TRANSACAO] [varchar](255) NOT NULL,
	[E_ENTRADA] [bit] NOT NULL DEFAULT ((0)),
	[E_BANCO] [bit] NOT NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[ID_TIPO_TRANSACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


