USE [AGABRENWILL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ESTADO_CIVIL](
	[ID_ESTADO_CIVIL] [int] IDENTITY(1,1) NOT NULL,
	[DE_ESTADO_CIVIL] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ESTADO_CIVIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


