USE [AGABRENWILL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[REGRA_DISTRIBUICAO](
	[ID_REGRA_DISTRIBUICAO] [int] IDENTITY(1,1) NOT NULL,
	[DE_REGRA] [varchar](255) NOT NULL,
	[VL_PARTICIPACAO] [float] NULL,
	[ID_GRUPO_REGRA_DISTRIBUICAO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_REGRA_DISTRIBUICAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[REGRA_DISTRIBUICAO]  WITH CHECK ADD  CONSTRAINT [FK_GRUPO_REGRA_DISTRIBUICAO_REGRA] FOREIGN KEY([ID_GRUPO_REGRA_DISTRIBUICAO])
REFERENCES [dbo].[GRUPO_REGRA_DISTRIBUICAO] ([ID_GRUPO_REGRA_DISTRIBUICAO])
GO

ALTER TABLE [dbo].[REGRA_DISTRIBUICAO] CHECK CONSTRAINT [FK_GRUPO_REGRA_DISTRIBUICAO_REGRA]
GO


