USE [AGABRENWILL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GRUPO_REGRA_DISTRIBUICAO](
	[ID_GRUPO_REGRA_DISTRIBUICAO] [int] IDENTITY(1,1) NOT NULL,
	[NM_GRUPO_REGRA_DISTRIBUICAO] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_GRUPO_REGRA_DISTRIBUICAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


