USE [AGABRENWILL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CLIENTE](
	[ID_CLIENTE] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](255) NOT NULL,
	[SOBRENOME] [varchar](255) NOT NULL,
	[DT_NASC] [date] NULL,
	[CPF] [varchar](11) NOT NULL,
	[NACIONALIDADE] [varchar](255) NOT NULL,
	[PROFISSAO] [varchar](255) NOT NULL,
	[DT_REGISTRO] [datetime] NOT NULL DEFAULT (getdate()),
	[ID_ESTADO_CIVIL] [int] NOT NULL,
	[RG] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_ESTADO_CIVIL_CLIENTE] FOREIGN KEY([ID_ESTADO_CIVIL])
REFERENCES [dbo].[ESTADO_CIVIL] ([ID_ESTADO_CIVIL])
GO

ALTER TABLE [dbo].[CLIENTE] CHECK CONSTRAINT [FK_ESTADO_CIVIL_CLIENTE]
GO


