USE [AGABRENWILL]
GO

/****** Object:  Table [dbo].[ENDERECO]    Script Date: 01/12/2021 18:11:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ENDERECO](
	[ID_ENDERECO] [int] IDENTITY(1,1) NOT NULL,
	[RUA] [varchar](255) NOT NULL,
	[NUMERO] [varchar](10) NOT NULL,
	[BAIRRO] [varchar](255) NOT NULL,
	[MUNICIPIO] [varchar](255) NOT NULL,
	[ESTADO] [varchar](2) NOT NULL,
	[ID_CLIENTE] [int] NOT NULL,
	[ID_TIPO_ENDERECO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ENDERECO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ENDERECO]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_ENDERECO] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[CLIENTE] ([ID_CLIENTE])
GO

ALTER TABLE [dbo].[ENDERECO] CHECK CONSTRAINT [FK_CLIENTE_ENDERECO]
GO

ALTER TABLE [dbo].[ENDERECO]  WITH CHECK ADD  CONSTRAINT [FK_TIPO_ENDERECO_ENDERECO] FOREIGN KEY([ID_TIPO_ENDERECO])
REFERENCES [dbo].[TIPO_ENDERECO] ([ID_TIPO_ENDERECO])
GO

ALTER TABLE [dbo].[ENDERECO] CHECK CONSTRAINT [FK_TIPO_ENDERECO_ENDERECO]
GO


