USE [AGABRENWILL]
GO

/****** Object:  Table [dbo].[TIPO_ENDERECO]    Script Date: 01/12/2021 18:11:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TIPO_ENDERECO](
	[ID_TIPO_ENDERECO] [int] IDENTITY(1,1) NOT NULL,
	[DE_TIPO_ENDERECO] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_TIPO_ENDERECO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


