USE [AGABRENWILL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTRATO](
	[ID_CONTRATO] [int] IDENTITY(1,1) NOT NULL,
	[DT_REGISTRO] [datetime] NOT NULL DEFAULT (getdate()),
	[DT_ASSINATURA] [datetime] NULL,
	[DT_INICIO_CONTRATO] [datetime] NULL,
	[DT_FIM_PREVISTA_CONTRATO] [datetime] NULL,
	[ID_CLIENTE] [int] NOT NULL,
	[VL_TOTAL_CONTRATO] [decimal](10, 2) NOT NULL DEFAULT ((0)),
	[ID_GRUPO_REGRA_DISTRIBUICAO] [int] NOT NULL DEFAULT ((1)),
PRIMARY KEY CLUSTERED 
(
	[ID_CONTRATO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CONTRATO]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_CONTRATO] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[CLIENTE] ([ID_CLIENTE])
GO

ALTER TABLE [dbo].[CONTRATO] CHECK CONSTRAINT [FK_CLIENTE_CONTRATO]
GO

ALTER TABLE [dbo].[CONTRATO]  WITH CHECK ADD  CONSTRAINT [FK_GRUPO_REGRA_DISTRIBUICAO_CONTRATO] FOREIGN KEY([ID_GRUPO_REGRA_DISTRIBUICAO])
REFERENCES [dbo].[GRUPO_REGRA_DISTRIBUICAO] ([ID_GRUPO_REGRA_DISTRIBUICAO])
GO

ALTER TABLE [dbo].[CONTRATO] CHECK CONSTRAINT [FK_GRUPO_REGRA_DISTRIBUICAO_CONTRATO]
GO


