USE [AGABRENWILL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TRANSACAO_ADMINISTRATIVA](
	[ID_TRANSACAO_ADMINISTRATIVA] [int] IDENTITY(1,1) NOT NULL,
	[DT_REGISTRO] [datetime] NOT NULL,
	[DT_TRANSACAO] [datetime] NOT NULL,
	[VL_TRANSACAO] [decimal](10, 2) NULL,
	[DE_TRANSACAO] [varchar](255) NULL,
	[DE_TIPO_TRANSACAO] [varchar](255) NULL,
	[ID_TIPO_TRANSACAO] [int] NOT NULL,
	[ID_STATUS_TRANSACAO] [int] NOT NULL,
	[DT_LIMITE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_TRANSACAO_ADMINISTRATIVA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TRANSACAO_ADMINISTRATIVA] ADD  DEFAULT (getdate()) FOR [DT_REGISTRO]
GO

ALTER TABLE [dbo].[TRANSACAO_ADMINISTRATIVA]  WITH CHECK ADD  CONSTRAINT [FK_STATUS_TRANSACAO_TRANSACAO_ADMINISTRATIVA] FOREIGN KEY([ID_STATUS_TRANSACAO])
REFERENCES [dbo].[STATUS_TRANSACAO] ([ID_STATUS_TRANSACAO])
GO

ALTER TABLE [dbo].[TRANSACAO_ADMINISTRATIVA] CHECK CONSTRAINT [FK_STATUS_TRANSACAO_TRANSACAO_ADMINISTRATIVA]
GO

ALTER TABLE [dbo].[TRANSACAO_ADMINISTRATIVA]  WITH CHECK ADD  CONSTRAINT [FK_TIPO_TRANSACAO_TRANSACAO_ADMINISTRATIVA] FOREIGN KEY([ID_TIPO_TRANSACAO])
REFERENCES [dbo].[TIPO_TRANSACAO] ([ID_TIPO_TRANSACAO])
GO

ALTER TABLE [dbo].[TRANSACAO_ADMINISTRATIVA] CHECK CONSTRAINT [FK_TIPO_TRANSACAO_TRANSACAO_ADMINISTRATIVA]
GO


