USE [AGABRENWILL]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[STATUS_TRANSACAO](
	[ID_STATUS_TRANSACAO] [int] IDENTITY(1,1) NOT NULL,
	[DE_STATUS_TRANSACAO] [varchar](255) NOT NULL,
	[E_FINALIZADA] [bit] NOT NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[ID_STATUS_TRANSACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


